//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorMed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dados
    {
        public System.DateTime dt_medicao_dados { get; set; }
        public int cd_sensor { get; set; }
        public double vl_medicao_dados { get; set; }
    
        public virtual Sensor Sensor { get; set; }
    }
}
