//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorMed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int cd_usuario { get; set; }
        public string nm_uuario { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public string email { get; set; }
    }
}
